CREATE TABLE USER (
    USER_ID BIGINT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    NAME VARCHAR(50) NOT NULL,
    EMAIL VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(150) NOT NULL,
    ROLE VARCHAR(20) NOT NULL
)